# Generated by Django 5.1.7 on 2025-03-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
